def Data():
    sharecodes = [
        {
            'unique_id': '1',
            'game': 'forza_horizon_4_2018',
            'code': '123456789',
            'title': 'My First ShareCODe',
            'description': 'provide optional description about the share code is less than dont-make-it-boooooring words.',
            'author': 'speedy_gonzales',
            'preview_img_url': 'https://i2.paste.pics/FRU1O.png',
            'embed_yt_url': 'https://www.youtube.com/watch?v=U3mEOHvSUyw',
            'date': '2021-12-01',
            'upvotes': 10,
            'downvotes': 4,
            'views': 54,
        },
        {
            'unique_id': '2',
            'game': 'forza_horizon_5_2018',
            'code': '123789456',
            'title': 'My next best Sharec0de',
            'description': 'HAHAHA Car Go Brrrrrrrrr',
            'author': 'bono',
            'preview_img_url': 'https://i2.paste.pics/FRU28.png',
            'embed_yt_url': 'https://www.youtube.com/watch?v=BoxkZrmkSFE',
            'date': '2019-10-12',
            'upvotes': 67,
            'downvotes': 12,
            'views': 762,
        },
        {
            'unique_id': '3',
            'game': 'forza_horizon_5_2018',
            'code': '123456946',
            'title': 'All i want is to share codes',
            'description': 'just another stupid option description',
            'author': 'john honai',
            'preview_img_url': 'https://i2.paste.pics/FTB0E.png',
            'embed_yt_url': 'https://www.youtube.com/watch?v=fdGWRq1dVBA',
            'date': '2021-04-01',
            'upvotes': 100,
            'downvotes': 1343,
            'views': 65200,
        },
        {
            'unique_id': "4a5g6",
            'game': 'forza_horizon_5_2018',
            'code': '123489456',
            'title': 'marvel uyir',
            'description': 'iron man dies lol',
            'author': 'thanos',
            'preview_img_url': 'https://i2.paste.pics/FTB8A.png',
            'embed_yt_url': 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
            'date': '2019-01-02',
            'upvotes': 67,
            'downvotes': 92,
            'views': 456,
        }
    ]
    return sharecodes